package Model.SpaceShip;

public enum ComponentType {
    SINGLE_ENGINE,
    DOUBLE_ENGINE,
    SINGLE_CANNON,
    DOUBLE_CANNON,
    CABIN,
    CENTER_CABIN,
    STORAGE,
    PURPLE_LIFE_SUPPORT,
    BROWN_LIFE_SUPPORT,
    BATTERY,
    SHIELD,
    CONNECTORS
}
